HZA-37 adding IAS updates

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,7 +4,7 @@ orbs:
   ruby: circleci/ruby@2.0
   node: circleci/node@5
   aws-cli: circleci/aws-cli@3.1
-  terraform: circleci/terraform@2.0.1
+  terraform: circleci/terraform@2
 
 executors:
   circle-machine:
@@ -41,19 +41,96 @@ executors:
           POSTGRES_DB: hzgeo
 
 commands:
-  configure-ecr-environment:
+  aws-init:
+    parameters:
+      registry-id:
+        type: string
+        default: '222484291001'
+      image-name:
+        type: string
+        default: 'hubzone-api'
+      region:
+        type: string
+        description: A default AWS region name
+        default: us-east-1
+    steps:
+      - aws-cli/setup:
+          role-arn: $OIDC_ROLE_ARN
+          role-session-name: oidc-certify-hubzone-api
+      - run:
+          name: aws-init
+          command: |
+            echo 'AWS_ECR_REGISTRY_ENDPOINT="<< parameters.registry-id >>.dkr.ecr.<< parameters.region >>.amazonaws.com"' >> $BASH_ENV
+            echo 'AWS_ECR_IMAGE_NAME="${AWS_ECR_REGISTRY_ENDPOINT}/<< parameters.image-name >>"' >> $BASH_ENV
+            source $BASH_ENV
+
+  ecr-login:
+    steps:
+      - run:
+          name: ecr docker login
+          command: |
+            aws_version=`aws --version 2>&1`
+            if echo $aws_version | grep 'aws-cli/1' > /dev/null; then
+              echo "aws-cli v1 detected. Logging in to ecr docker..."
+              `aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION}`
+            elif echo $aws_version | grep 'aws-cli/2' > /dev/null; then
+              echo "aws-cli v2 detected. Logging in to ecr docker..."
+              aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin "${AWS_ECR_REGISTRY_ENDPOINT}"
+            else
+              echo "Can't detect the version of awscli being used..."
+              exit 1
+            fi
+
+  ecr-image-build:
+    parameters:
+      dockerfile:
+        type: string
+        default: Dockerfile
+      image-name:
+        type: string
+        default: 'hubzone-api'
+    steps:
+      - run:
+          name: Build << parameters.dockerfile >> docker image
+          command: |
+            docker image build . -f "<< parameters.dockerfile >>" --tag "${AWS_ECR_REGISTRY_ENDPOINT}/<< parameters.image-name >>:${CIRCLE_SHA1}"
+  ecr-image-push:
     parameters:
       image-name:
         type: string
-        default: hubzone/hubzone-api
     steps:
-      - run:
-          name: Configure ECR Build Environment
-          command: |
-            echo 'AWS_ACCOUNT_ID="`aws sts get-caller-identity --query Account --output text`"' >> $BASH_ENV
-            echo 'AWS_ECR_REGISTRY_ENDPOINT="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"' >> $BASH_ENV
-            echo 'AWS_ECR_IMAGE_NAME="${AWS_ECR_REGISTRY_ENDPOINT}/<< parameters.image-name >>"' >> $BASH_ENV
-            source $BASH_ENV
+    - deploy:
+        name: docker image push
+        command: |
+          docker image tag "${AWS_ECR_REGISTRY_ENDPOINT}/<< parameters.image-name >>:${CIRCLE_SHA1}" \
+                           "${AWS_ECR_REGISTRY_ENDPOINT}/<< parameters.image-name >>:${CIRCLE_BRANCH:-${CIRCLE_TAG:-NO_BRANCH_OR_TAG_CONFIGURED_BY_CIRCLE}}"
+          docker image push "${AWS_ECR_REGISTRY_ENDPOINT}/<< parameters.image-name >>:${CIRCLE_SHA1}"
+          echo "Successfully pushed image: ${AWS_ECR_REGISTRY_ENDPOINT}/<< parameters.image-name >>:${CIRCLE_SHA1}"
+          docker image push "${AWS_ECR_REGISTRY_ENDPOINT}/<< parameters.image-name >>:${CIRCLE_BRANCH:-${CIRCLE_TAG:-NO_BRANCH_OR_TAG_CONFIGURED_BY_CIRCLE}}"
+          echo "Successfully pushed image: ${AWS_ECR_REGISTRY_ENDPOINT}/<< parameters.image-name >>:${CIRCLE_BRANCH:-${CIRCLE_TAG:-NO_BRANCH_OR_TAG_CONFIGURED_BY_CIRCLE}}"
+  build-image:
+    steps:
+    - ecr-image-build:
+        image-name: hubzone-api
+
+  push-image:
+    steps:
+    - ecr-image-push:
+        image-name: hubzone-api
+
+  # configure-ecr-environment:
+  #   parameters:
+  #     image-name:
+  #       type: string
+  #       default: hubzone/hubzone-api
+  #   steps:
+  #     - run:
+  #         name: Configure ECR Build Environment
+  #         command: |
+  #           echo 'AWS_ACCOUNT_ID="`aws sts get-caller-identity --query Account --output text`"' >> $BASH_ENV
+  #           echo 'AWS_ECR_REGISTRY_ENDPOINT="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"' >> $BASH_ENV
+  #           echo 'AWS_ECR_IMAGE_NAME="${AWS_ECR_REGISTRY_ENDPOINT}/<< parameters.image-name >>"' >> $BASH_ENV
+  #           source $BASH_ENV
 
 jobs:
   rubocop:
@@ -160,28 +237,29 @@ jobs:
         default: hubzone/hubzone-api
     steps:
       - checkout
-      - aws-cli/setup:
-          role-arn: $OIDC_ROLE_ARN
-          role-session-name: oidc-hubzone-webmap
-      - configure-ecr-environment:
-          image-name: << parameters.image-name >>
-      - run:
-          name: Login to ECR registry
-          command: |
-            aws ecr get-login-password --region $AWS_REGION | \
-              docker login --username AWS --password-stdin $AWS_ECR_REGISTRY_ENDPOINT
-      - run:
-          name: Build and Push Container
-          command: |
-            docker image build -t webmap:latest .
-            echo "Pushing Image: ${AWS_ECR_IMAGE_NAME}:<< parameters.image-tag >>"
-            docker image tag webmap:latest "${AWS_ECR_IMAGE_NAME}:<< parameters.image-tag >>"
-            docker image push "${AWS_ECR_IMAGE_NAME}:<< parameters.image-tag >>"
-            echo "Push complete!"
-            echo "Pushing Image: ${AWS_ECR_IMAGE_NAME}:${CIRCLE_SHA1}"
-            docker image tag webmap:latest "${AWS_ECR_IMAGE_NAME}:${CIRCLE_SHA1}"
-            docker image push "${AWS_ECR_IMAGE_NAME}:${CIRCLE_SHA1}"
-            echo "Push complete!"
+      - aws-init
+      - ecr-login
+      - build-image
+      - push-image
+      # - configure-ecr-environment:
+      #     image-name: << parameters.image-name >>
+      # - run:
+      #     name: Login to ECR registry
+      #     command: |
+      #       aws ecr get-login-password --region $AWS_REGION | \
+      #         docker login --username AWS --password-stdin $AWS_ECR_REGISTRY_ENDPOINT
+      # - run:
+      #     name: Build and Push Container
+      #     command: |
+      #       docker image build -t webmap:latest .
+      #       echo "Pushing Image: ${AWS_ECR_IMAGE_NAME}:<< parameters.image-tag >>"
+      #       docker image tag webmap:latest "${AWS_ECR_IMAGE_NAME}:<< parameters.image-tag >>"
+      #       docker image push "${AWS_ECR_IMAGE_NAME}:<< parameters.image-tag >>"
+      #       echo "Push complete!"
+      #       echo "Pushing Image: ${AWS_ECR_IMAGE_NAME}:${CIRCLE_SHA1}"
+      #       docker image tag webmap:latest "${AWS_ECR_IMAGE_NAME}:${CIRCLE_SHA1}"
+      #       docker image push "${AWS_ECR_IMAGE_NAME}:${CIRCLE_SHA1}"
+      #       echo "Push complete!"
       - run:
           name: Logout of ECR registry
           command: |
